import React, { useEffect } from "react";
import styled from "styled-components";
import media from "../media";

const StyledLoaderContainer = styled.div`
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
`;

const StyledLoader = styled.div`
    .cls-1 {
        stroke: #000;
        stroke-miterlimit: 10;
        stroke-width: 2px;
    }
    .cls-2 {
        fill: #414042;
    }
    .cls-3 {
        fill: #231f20;
    }
    .cls-4 {
        fill: #a7a9ac;
    }
    .cls-5 {
        fill: #bcbec0;
    }
    /***************************************************
 * Generated by SVG Artista on 10/11/2020, 2:05:39 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

    svg {
        width: 60vw;

        ${media.lessThan("medium")`
            width: 95vw;
        `}
    }

    svg .svg-elem-1 {
        stroke-dashoffset: 154.52000427246094px;
        stroke-dasharray: 154.52000427246094px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
    }

    svg.active .svg-elem-1 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-2 {
        stroke-dashoffset: 205.18019104003906px;
        stroke-dasharray: 205.18019104003906px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.12s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
    }

    svg.active .svg-elem-2 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-3 {
        stroke-dashoffset: 192.25054931640625px;
        stroke-dasharray: 192.25054931640625px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.24s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
    }

    svg.active .svg-elem-3 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-4 {
        stroke-dashoffset: 154.52000427246094px;
        stroke-dasharray: 154.52000427246094px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.36s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
    }

    svg.active .svg-elem-4 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-5 {
        stroke-dashoffset: 192.30667114257812px;
        stroke-dasharray: 192.30667114257812px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.48s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
    }

    svg.active .svg-elem-5 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-6 {
        stroke-dashoffset: 182.6975860595703px;
        stroke-dasharray: 182.6975860595703px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.6s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
    }

    svg.active .svg-elem-6 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-7 {
        stroke-dashoffset: 184.8169708251953px;
        stroke-dasharray: 184.8169708251953px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.72s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
    }

    svg.active .svg-elem-7 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-8 {
        stroke-dashoffset: 169.6847686767578px;
        stroke-dasharray: 169.6847686767578px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.84s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
    }

    svg.active .svg-elem-8 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-9 {
        stroke-dashoffset: 143.46194458007812px;
        stroke-dasharray: 143.46194458007812px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.96s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
    }

    svg.active .svg-elem-9 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-10 {
        stroke-dashoffset: 188.72247314453125px;
        stroke-dasharray: 188.72247314453125px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.08s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
    }

    svg.active .svg-elem-10 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-11 {
        stroke-dashoffset: 150.867431640625px;
        stroke-dasharray: 150.867431640625px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.2s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
    }

    svg.active .svg-elem-11 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-12 {
        stroke-dashoffset: 208.1418914794922px;
        stroke-dasharray: 208.1418914794922px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.3199999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s;
    }

    svg.active .svg-elem-12 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-13 {
        stroke-dashoffset: 182.70567321777344px;
        stroke-dasharray: 182.70567321777344px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.44s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s;
    }

    svg.active .svg-elem-13 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-14 {
        stroke-dashoffset: 214.53773498535156px;
        stroke-dasharray: 214.53773498535156px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.56s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s;
    }

    svg.active .svg-elem-14 {
        stroke-dashoffset: 0;
        fill: rgb(65, 64, 66);
    }

    svg .svg-elem-15 {
        stroke-dashoffset: 613.5953979492188px;
        stroke-dasharray: 613.5953979492188px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.68s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s;
    }

    svg.active .svg-elem-15 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-16 {
        stroke-dashoffset: 122.91931915283203px;
        stroke-dasharray: 122.91931915283203px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.7999999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.7999999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s;
    }

    svg.active .svg-elem-16 {
        stroke-dashoffset: 0;
        fill: rgb(167, 169, 172);
    }

    svg .svg-elem-17 {
        stroke-dashoffset: 228.87330627441406px;
        stroke-dasharray: 228.87330627441406px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.92s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.92s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s;
    }

    svg.active .svg-elem-17 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-18 {
        stroke-dashoffset: 71.49703979492188px;
        stroke-dasharray: 71.49703979492188px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.04s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s;
    }

    svg.active .svg-elem-18 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-19 {
        stroke-dashoffset: 32.64295959472656px;
        stroke-dasharray: 32.64295959472656px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.16s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.16s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s;
    }

    svg.active .svg-elem-19 {
        stroke-dashoffset: 0;
        fill: rgb(188, 190, 192);
    }

    svg .svg-elem-20 {
        stroke-dashoffset: 59.49979019165039px;
        stroke-dasharray: 59.49979019165039px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.28s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.28s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s;
    }

    svg.active .svg-elem-20 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-21 {
        stroke-dashoffset: 238.18402099609375px;
        stroke-dasharray: 238.18402099609375px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.4s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.4s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s;
    }

    svg.active .svg-elem-21 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-22 {
        stroke-dashoffset: 32.588409423828125px;
        stroke-dasharray: 32.588409423828125px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.52s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.52s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s;
    }

    svg.active .svg-elem-22 {
        stroke-dashoffset: 0;
        fill: rgb(167, 169, 172);
    }

    svg .svg-elem-23 {
        stroke-dashoffset: 61.71234893798828px;
        stroke-dasharray: 61.71234893798828px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.6399999999999997s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.6399999999999997s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s;
    }

    svg.active .svg-elem-23 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-24 {
        stroke-dashoffset: 59.52915573120117px;
        stroke-dasharray: 59.52915573120117px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.76s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.76s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s;
    }

    svg.active .svg-elem-24 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-25 {
        stroke-dashoffset: 7.948788642883301px;
        stroke-dasharray: 7.948788642883301px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.88s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.88s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s;
    }

    svg.active .svg-elem-25 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-26 {
        stroke-dashoffset: 7.973469257354736px;
        stroke-dasharray: 7.973469257354736px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 3s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 3s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s;
    }

    svg.active .svg-elem-26 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }
`;

const Loader = (props) => {
    useEffect(() => {
        // effect
        const start = setTimeout(() => {
            document.getElementById("logo").classList.add("active");
        }, 10);
        const erase = setTimeout(() => {
            document.getElementById("logo").classList.remove("active");
        }, 4000);
        const end = setTimeout(() => {
            if (props.onFinishLoad) {
                props.onFinishLoad();
            }
        }, 7010);
        return () => {
            // cleanup
            clearTimeout(start);
            clearTimeout(erase);
            clearTimeout(end);
        };
    }, [props]);

    return (
        <StyledLoaderContainer>
            <StyledLoader>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    id="logo"
                    viewBox="0 0 637.52 107.41"
                    width="637.52001953125"
                    height="107.41000366210938"
                >
                    <defs>
                        <style></style>
                    </defs>
                    <title>Asset 1</title>
                    <g id="Layer_2" data-name="Layer 2">
                        <g id="Layer_3" data-name="Layer 3">
                            <path
                                class="cls-1 svg-elem-1"
                                d="M180,79.06h-6.7V39.94H161.17v-6.2h30.94v6.2H180Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-2"
                                d="M224.29,47.6a12.36,12.36,0,0,1,3,8.77V79.06h-6.7v-22a7.16,7.16,0,0,0-1.8-5.2,7.33,7.33,0,0,0-9.89.12,7.83,7.83,0,0,0-1.83,5.52V79.06h-6.69V33.8h6.69V45l-.06,6.51h.12A7.61,7.61,0,0,1,210,46.2a9.7,9.7,0,0,1,6.2-1.86A10.6,10.6,0,0,1,224.29,47.6Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-3"
                                d="M264.65,63.62H243.82v2.86a8.2,8.2,0,0,0,1.83,5.76,7,7,0,0,0,5.42,2,8.89,8.89,0,0,0,4.62-1,4.45,4.45,0,0,0,2.14-3h6.69a10.27,10.27,0,0,1-4.4,6.91A15.47,15.47,0,0,1,251,79.68q-6.27,0-9.95-3.62a12.85,12.85,0,0,1-3.69-9.58V57.55a12.81,12.81,0,0,1,3.69-9.61q3.69-3.6,9.95-3.6t9.95,3.6a12.81,12.81,0,0,1,3.69,9.61ZM243.82,59.1,258.2,59V57.49a8.34,8.34,0,0,0-1.83-5.8,6.89,6.89,0,0,0-5.36-2,6.81,6.81,0,0,0-5.36,2,8.45,8.45,0,0,0-1.83,5.83Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-4"
                                d="M291.56,79.06h-6.7V39.94H272.77v-6.2h30.94v6.2H291.56Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-5"
                                d="M339.05,63.62H318.22v2.86A8.19,8.19,0,0,0,320,72.24a7,7,0,0,0,5.43,2,8.89,8.89,0,0,0,4.62-1,4.49,4.49,0,0,0,2.14-3h6.69a10.27,10.27,0,0,1-4.4,6.91,15.5,15.5,0,0,1-9.11,2.57q-6.27,0-10-3.62a12.85,12.85,0,0,1-3.69-9.58V57.55a12.81,12.81,0,0,1,3.69-9.61q3.68-3.6,10-3.6t9.95,3.6a12.81,12.81,0,0,1,3.69,9.61ZM318.22,59.1,332.6,59V57.49a8.34,8.34,0,0,0-1.83-5.8,8.09,8.09,0,0,0-10.73,0,8.45,8.45,0,0,0-1.82,5.83Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-6"
                                d="M373.08,47.6q3,3.26,3,8.77V79.06h-6.69v-22a7.16,7.16,0,0,0-1.8-5.2,7.33,7.33,0,0,0-9.89.12,7.83,7.83,0,0,0-1.83,5.52V79.06h-6.7V45h6.64v6.51H356a7.64,7.64,0,0,1,2.79-5.27,9.72,9.72,0,0,1,6.2-1.86A10.57,10.57,0,0,1,373.08,47.6Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-7"
                                d="M398.44,79.68a14.36,14.36,0,0,1-8.9-2.57,9.14,9.14,0,0,1-3.69-6.91h6.7a4,4,0,0,0,1.8,2.79A7.17,7.17,0,0,0,398.44,74h2.61a7.19,7.19,0,0,0,4.58-1.24,4,4,0,0,0,1.55-3.35,3.79,3.79,0,0,0-1.36-3.1,8.6,8.6,0,0,0-4.09-1.55l-4.4-.68q-5.52-.81-8.1-3.13t-2.57-6.73A9,9,0,0,1,389.79,47q3.13-2.61,9.09-2.61h2.35a13.72,13.72,0,0,1,8.46,2.45,9.1,9.1,0,0,1,3.69,6.6h-6.69A3.79,3.79,0,0,0,405,50.91a6.7,6.7,0,0,0-3.72-.93h-2.35q-5.58,0-5.58,4.34a3.43,3.43,0,0,0,1.11,2.79,7.64,7.64,0,0,0,3.72,1.31l4.46.68q5.84.87,8.53,3.25c1.8,1.6,2.7,3.9,2.7,6.92A9.46,9.46,0,0,1,410.56,77q-3.26,2.73-9.51,2.73Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-8"
                                d="M427,76.12q-3.66-3.57-3.66-9.64V57.55q0-6.07,3.66-9.64t10-3.57q6.33,0,10,3.54t3.65,9.61v9q0,6.08-3.65,9.64t-10,3.56Q430.69,79.68,427,76.12Zm15.13-4.19a7.54,7.54,0,0,0,1.8-5.45V57.55a7.55,7.55,0,0,0-1.8-5.46,8,8,0,0,0-10.29,0,7.55,7.55,0,0,0-1.8,5.46v8.93a7.54,7.54,0,0,0,1.8,5.45,8,8,0,0,0,10.29,0Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-9"
                                d="M486.2,47.72q3.19,3.38,3.19,9.27v2.29h-6.88V57.55A7.92,7.92,0,0,0,480.68,52a7.57,7.57,0,0,0-10.23,0,7.92,7.92,0,0,0-1.83,5.58V79.06h-6.69V45h6.45v6.39q1.61-7,9.17-7A11.34,11.34,0,0,1,486.2,47.72Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-10"
                                d="M501.51,76.12a12.68,12.68,0,0,1-3.75-9.64V46.39q0-6.07,3.75-9.64t10.14-3.57c4.22,0,7.57,1.2,10.08,3.6a12.7,12.7,0,0,1,3.75,9.61h-6.7a7.46,7.46,0,0,0-1.86-5.4,7,7,0,0,0-5.27-1.92,7.17,7.17,0,0,0-5.3,1.89,7.26,7.26,0,0,0-1.89,5.37V66.48a7.36,7.36,0,0,0,1.89,5.39,7.11,7.11,0,0,0,5.3,1.92,7,7,0,0,0,5.24-1.92,7.36,7.36,0,0,0,1.89-5.39h6.7a12.7,12.7,0,0,1-3.75,9.61c-2.51,2.39-5.86,3.59-10.08,3.59S504,78.49,501.51,76.12Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-11"
                                d="M553.13,79.06a10.55,10.55,0,0,1-7.72-2.82,10.06,10.06,0,0,1-2.88-7.53V39.88h-10.3V33.8h17V68.71a4.29,4.29,0,0,0,1.12,3.13,4,4,0,0,0,3,1.15h11v6.07Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-12"
                                d="M595.78,47.44a10.39,10.39,0,0,1,3.54,8.31V79.06h-6.51V72.8h-.06a6.91,6.91,0,0,1-3.32,5,13,13,0,0,1-7.16,1.86A11.94,11.94,0,0,1,574,76.92a9.46,9.46,0,0,1-3.07-7.41,9.72,9.72,0,0,1,3.23-7.75c2.14-1.86,5.14-2.79,9-2.79h9.49v-3.1a5.43,5.43,0,0,0-1.74-4.31,7.3,7.3,0,0,0-5-1.51,8.35,8.35,0,0,0-4.61,1.14,4.67,4.67,0,0,0-2.14,3.2h-6.58a10.31,10.31,0,0,1,4.22-7.26,15,15,0,0,1,9.24-2.73Q592.24,44.4,595.78,47.44ZM590.3,72.77A5.65,5.65,0,0,0,592.62,68V63.56h-9.36A5.7,5.7,0,0,0,579.14,65,5.17,5.17,0,0,0,577.62,69a5.08,5.08,0,0,0,1.76,4.09,7.24,7.24,0,0,0,4.81,1.49A9.83,9.83,0,0,0,590.3,72.77Z"
                            ></path>
                            <path
                                class="cls-1 svg-elem-13"
                                d="M633.48,47.6a12.36,12.36,0,0,1,3,8.77V79.06h-6.7v-22a7.16,7.16,0,0,0-1.8-5.2,7.33,7.33,0,0,0-9.89.12,7.83,7.83,0,0,0-1.83,5.52V79.06h-6.69V45h6.63v6.51h.13a7.64,7.64,0,0,1,2.79-5.27,9.7,9.7,0,0,1,6.2-1.86A10.58,10.58,0,0,1,633.48,47.6Z"
                            ></path>
                            <rect
                                class="cls-2 svg-elem-14"
                                x="130.2"
                                y="2.12"
                                width="5.83"
                                height="103.17"
                                rx="2.91"
                            ></rect>
                            <path
                                class="cls-3 svg-elem-15"
                                d="M62.79,107.41a1,1,0,0,1-.57-.19,1,1,0,0,1-.34-1,65.63,65.63,0,0,0,2.35-12.14v0c.75-7.77.23-18.41-6.55-25-7-6.77-19.8-8.32-24-8.82a65.66,65.66,0,0,0-8.61-.42h-.56c-4.23,0-7.58.06-11.81-2C7.46,55.29,3.22,50.65.09,44.06a1,1,0,0,1,1.59-1,24.82,24.82,0,0,0,7.48,6.23,17.85,17.85,0,0,0,2.09-6.63.92.92,0,0,1,.67-.8,22.23,22.23,0,0,0,3.86-1.55c4-2.09,6.31-4.92,8.7-7.91a38,38,0,0,1,8.79-8.65,34.1,34.1,0,0,1,5.92-3.21,37.43,37.43,0,0,1,8.65-2.44A31.59,31.59,0,0,1,50.2,10c.29-.66.61-1.31.93-1.92A31.33,31.33,0,0,1,56.91.27a.94.94,0,0,1,1.2-.1A27.85,27.85,0,0,1,68.32,13.38a27.43,27.43,0,0,1,1.45,11.91A51.38,51.38,0,0,1,86.32,52.92c3.93,18-3.37,32.43-6.69,37.8h0a51.77,51.77,0,0,1-11.89,13.36h0l0,0c-1.41,1.12-2.9,2.18-4.42,3.16A1,1,0,0,1,62.79,107.41Zm3.33-13.22v0a68.22,68.22,0,0,1-1.75,10c.75-.53,1.47-1.08,2.18-1.64h0l0,0A50,50,0,0,0,78,89.73h0c3.2-5.18,10.23-19.1,6.45-36.4A49.59,49.59,0,0,0,68.17,26.4a.93.93,0,0,1-.33-.83A25.52,25.52,0,0,0,66.54,14,25.78,25.78,0,0,0,57.67,2.19,29.8,29.8,0,0,0,52.8,8.92q-.45.87-.87,1.8A29.77,29.77,0,0,0,49.62,19a1,1,0,0,1-.8.82,36.1,36.1,0,0,0-8.9,2.41,32.37,32.37,0,0,0-5.59,3A36.71,36.71,0,0,0,26,33.57c-2.52,3.15-4.91,6.13-9.31,8.41a22.61,22.61,0,0,1-3.6,1.5A19.71,19.71,0,0,1,10.33,51a1,1,0,0,1-1.22.36A25,25,0,0,1,5.23,49a22.76,22.76,0,0,0,8.3,7.11C17.37,58,20.36,58,24.51,58h.56a67.73,67.73,0,0,1,8.84.43c4.36.53,17.62,2.13,25.09,9.34C66.32,74.78,66.91,86,66.12,94.19Zm1,9.15Z"
                            ></path>
                            <path
                                class="cls-4 svg-elem-16"
                                d="M65.18,94.12A32.86,32.86,0,0,0,53.64,72.77c-7.45-6-16.16-7-21.72-6.8a25.53,25.53,0,0,0-6.85-7.08,64.84,64.84,0,0,1,8.73.42c4.42.53,17.3,2.09,24.54,9.08C65.28,75.09,66,85.74,65.18,94.12Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-17"
                                d="M65.18,95.07a1,1,0,0,1-.94-.82A31.82,31.82,0,0,0,53,73.51C46,67.79,37.66,66.77,32,66.91a1,1,0,0,1-.83-.44,24.71,24.71,0,0,0-6.6-6.81,1,1,0,0,1-.35-1.06,1,1,0,0,1,.9-.66,67.73,67.73,0,0,1,8.84.43c4.36.53,17.62,2.13,25.09,9.34S66.91,86,66.12,94.21a1,1,0,0,1-.92.86ZM33,65c6,0,14.16,1.3,21.26,7A32.49,32.49,0,0,1,64.46,86.94c-.26-6.35-1.9-13.16-6.77-17.87-7-6.77-19.8-8.32-24-8.82a54.92,54.92,0,0,0-5.87-.4A25.78,25.78,0,0,1,32.43,65Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-18"
                                d="M18.92,90.6A.94.94,0,0,1,18,90a.93.93,0,0,1,.58-1.2c.55-.2,13.66-4.91,14.83-13.54a13.42,13.42,0,0,0-2.32-8.75.95.95,0,0,1,1.6-1,15.11,15.11,0,0,1,2.6,10C34,85.24,19.84,90.33,19.23,90.54A.85.85,0,0,1,18.92,90.6Z"
                            ></path>
                            <path
                                class="cls-5 svg-elem-19"
                                d="M12.19,42.75a18.87,18.87,0,0,1-2.66,7.79A26,26,0,0,1,1,43.65,29.17,29.17,0,0,0,12.19,42.75Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-20"
                                d="M9.53,51.48a1,1,0,0,1-.42-.09A26.73,26.73,0,0,1,.22,44.26a.94.94,0,0,1-.11-1,1,1,0,0,1,.93-.5,28.89,28.89,0,0,0,10.88-.86,1,1,0,0,1,1.21,1A19.8,19.8,0,0,1,10.33,51,.93.93,0,0,1,9.53,51.48ZM3.2,44.75a24.37,24.37,0,0,0,6,4.53A17.82,17.82,0,0,0,11,44,30.08,30.08,0,0,1,3.2,44.75Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-21"
                                d="M62.79,107.41a.94.94,0,0,1-.82-.49.93.93,0,0,1,.36-1.28,24.17,24.17,0,0,0,4.18-3h0l0,0c7.57-6.79,12.88-20.47,7.83-32.5-5.45-13-20.92-17.68-30.09-17.68h-.15c-1.57,0-3,.15-5.09.35-3,.28-7,.68-14,.9-6.6.22-10,.07-13.9-1.41-.68-.26-1.36-.56-2-.88a.95.95,0,0,1,.42-1.8,1,1,0,0,1,.47.13c.59.29,1.2.55,1.81.78,3.6,1.36,6.83,1.5,13.17,1.29,6.93-.22,11-.61,13.89-.9,2.09-.2,3.6-.35,5.26-.35a41.11,41.11,0,0,1,17.43,4.12c6.91,3.39,12,8.48,14.56,14.72,5.4,12.86-.27,27.46-8.34,34.66l0,0a25.42,25.42,0,0,1-4.49,3.2A.84.84,0,0,1,62.79,107.41Z"
                            ></path>
                            <path
                                class="cls-4 svg-elem-22"
                                d="M34.44,39.53c-.54-1,.78-2.77,1.29-3.48a8.48,8.48,0,0,1,2.39-2.19,31.8,31.8,0,0,1,4.05.39,31.29,31.29,0,0,1,5,1.22,15.8,15.8,0,0,1-6.44,4C38.89,40,35.17,40.82,34.44,39.53Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-23"
                                d="M36.5,41.17c-1.25,0-2.38-.28-2.88-1.17h0c-.85-1.5.64-3.53,1.35-4.51a9.2,9.2,0,0,1,2.65-2.43.89.89,0,0,1,.52-.14,31.44,31.44,0,0,1,9.3,1.66,1,1,0,0,1,.62.68.94.94,0,0,1-.26.88,16.74,16.74,0,0,1-11.3,5Zm-1.23-2.11c.29.36,2.48.34,5.14-.5a14.25,14.25,0,0,0,4.86-2.67A33,33,0,0,0,42,35.18a31.59,31.59,0,0,0-3.64-.36,7.29,7.29,0,0,0-1.88,1.79C35.13,38.48,35.24,39,35.27,39.06Zm0,0Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-24"
                                d="M39.55,22.35a.94.94,0,0,1-.93-.8,27.29,27.29,0,0,1,0-8.51A27.57,27.57,0,0,1,40.73,5.9a1,1,0,0,1,1-.54,22.51,22.51,0,0,1,9.88,4.23A.94.94,0,1,1,50.5,11.1a20.64,20.64,0,0,0-8.34-3.74,25.45,25.45,0,0,0-1.67,13.89,1,1,0,0,1-.79,1.09Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-25"
                                d="M65.18,95.07a1,1,0,0,1-1-.94h0a.95.95,0,1,1,1,.95Z"
                            ></path>
                            <path
                                class="cls-3 svg-elem-26"
                                d="M9.53,51.48a.94.94,0,0,1-.95-.94h0a.95.95,0,1,1,.95.94Z"
                            ></path>
                        </g>
                    </g>
                </svg>
            </StyledLoader>
        </StyledLoaderContainer>
    );
};

export default Loader;
