import React, { useEffect } from "react";
import styled from "styled-components";

const StyledLoaderContainer = styled.div`
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
`;

const StyledLoader = styled.div`
    .cls-1 {
        stroke: #000;
        stroke-miterlimit: 10;
        stroke-width: 2px;
    }
    .cls-2 {
        fill: #414042;
    }
    .cls-3 {
        fill: #231f20;
    }
    .cls-4 {
        fill: #a7a9ac;
    }
    .cls-5 {
        fill: #bcbec0;
    }
    /***************************************************
 * Generated by SVG Artista on 10/11/2020, 2:05:39 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

    svg {
        width: 80vw;
    }

    svg .svg-elem-1 {
        stroke-dashoffset: 154.5400390625px;
        stroke-dasharray: 154.5400390625px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
    }

    svg.active .svg-elem-1 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-2 {
        stroke-dashoffset: 205.04391479492188px;
        stroke-dasharray: 205.04391479492188px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.12s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
    }

    svg.active .svg-elem-2 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-3 {
        stroke-dashoffset: 192.22720336914062px;
        stroke-dasharray: 192.22720336914062px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.24s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
    }

    svg.active .svg-elem-3 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-4 {
        stroke-dashoffset: 154.5400390625px;
        stroke-dasharray: 154.5400390625px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.36s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
    }

    svg.active .svg-elem-4 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-5 {
        stroke-dashoffset: 192.33633422851562px;
        stroke-dasharray: 192.33633422851562px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.48s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
    }

    svg.active .svg-elem-5 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-6 {
        stroke-dashoffset: 182.69302368164062px;
        stroke-dasharray: 182.69302368164062px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.6s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
    }

    svg.active .svg-elem-6 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-7 {
        stroke-dashoffset: 184.8481903076172px;
        stroke-dasharray: 184.8481903076172px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.72s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
    }

    svg.active .svg-elem-7 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-8 {
        stroke-dashoffset: 169.75067138671875px;
        stroke-dasharray: 169.75067138671875px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.84s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
    }

    svg.active .svg-elem-8 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-9 {
        stroke-dashoffset: 143.57611083984375px;
        stroke-dasharray: 143.57611083984375px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                0.96s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
    }

    svg.active .svg-elem-9 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-10 {
        stroke-dashoffset: 188.71234130859375px;
        stroke-dasharray: 188.71234130859375px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.08s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
    }

    svg.active .svg-elem-10 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-11 {
        stroke-dashoffset: 150.86851501464844px;
        stroke-dasharray: 150.86851501464844px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.2s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
    }

    svg.active .svg-elem-11 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-12 {
        stroke-dashoffset: 208.1701202392578px;
        stroke-dasharray: 208.1701202392578px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.3199999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s;
    }

    svg.active .svg-elem-12 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-13 {
        stroke-dashoffset: 182.5566864013672px;
        stroke-dasharray: 182.5566864013672px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.44s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s;
    }

    svg.active .svg-elem-13 {
        stroke-dashoffset: 0;
        fill: rgb(0, 0, 0);
    }

    svg .svg-elem-14 {
        stroke-dashoffset: 214.5376739501953px;
        stroke-dasharray: 214.5376739501953px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.56s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s;
    }

    svg.active .svg-elem-14 {
        stroke-dashoffset: 0;
        fill: rgb(65, 64, 66);
    }

    svg .svg-elem-15 {
        stroke-dashoffset: 613.9793701171875px;
        stroke-dasharray: 613.9793701171875px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.68s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s;
    }

    svg.active .svg-elem-15 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-16 {
        stroke-dashoffset: 122.92208099365234px;
        stroke-dasharray: 122.92208099365234px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.7999999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.7999999999999998s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s;
    }

    svg.active .svg-elem-16 {
        stroke-dashoffset: 0;
        fill: rgb(167, 169, 172);
    }

    svg .svg-elem-17 {
        stroke-dashoffset: 228.94496154785156px;
        stroke-dasharray: 228.94496154785156px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 1.92s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                1.92s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s;
    }

    svg.active .svg-elem-17 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-18 {
        stroke-dashoffset: 71.70785522460938px;
        stroke-dasharray: 71.70785522460938px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.04s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s;
    }

    svg.active .svg-elem-18 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-19 {
        stroke-dashoffset: 32.730628967285156px;
        stroke-dasharray: 32.730628967285156px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.16s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.16s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s;
    }

    svg.active .svg-elem-19 {
        stroke-dashoffset: 0;
        fill: rgb(188, 190, 192);
    }

    svg .svg-elem-20 {
        stroke-dashoffset: 59.67963409423828px;
        stroke-dasharray: 59.67963409423828px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.28s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.28s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s;
    }

    svg.active .svg-elem-20 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-21 {
        stroke-dashoffset: 238.19113159179688px;
        stroke-dasharray: 238.19113159179688px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.4s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.4s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s;
    }

    svg.active .svg-elem-21 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-22 {
        stroke-dashoffset: 32.602365493774414px;
        stroke-dasharray: 32.602365493774414px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.52s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.52s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s;
    }

    svg.active .svg-elem-22 {
        stroke-dashoffset: 0;
        fill: rgb(167, 169, 172);
    }

    svg .svg-elem-23 {
        stroke-dashoffset: 61.70288848876953px;
        stroke-dasharray: 61.70288848876953px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.6399999999999997s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.6399999999999997s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s;
    }

    svg.active .svg-elem-23 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-24 {
        stroke-dashoffset: 59.268524169921875px;
        stroke-dasharray: 59.268524169921875px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.76s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.76s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s;
    }

    svg.active .svg-elem-24 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-25 {
        stroke-dashoffset: 7.950869083404541px;
        stroke-dasharray: 7.950869083404541px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 2.88s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715)
                2.88s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s;
    }

    svg.active .svg-elem-25 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }

    svg .svg-elem-26 {
        stroke-dashoffset: 7.973650932312012px;
        stroke-dasharray: 7.973650932312012px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s
                cubic-bezier(0.47, 0, 0.745, 0.715) 3s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 3s,
            fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s;
    }

    svg.active .svg-elem-26 {
        stroke-dashoffset: 0;
        fill: rgb(35, 31, 32);
    }
`;

const Loader = (props) => {
    useEffect(() => {
        // effect
        const start = setTimeout(() => {
            document.getElementById("logo").classList.add("active");
        }, 10);
        const erase = setTimeout(() => {
            document.getElementById("logo").classList.remove("active");
        }, 4000);
        const end = setTimeout(() => {
            if (props.onFinishLoad) {
                props.onFinishLoad();
            }
        }, 7010);
        return () => {
            // cleanup
            clearTimeout(start);
            clearTimeout(erase);
            clearTimeout(end);
        };
    }, [props]);

    return (
        <StyledLoaderContainer>
            <StyledLoader>
                <svg
                    id="logo"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 841.89 595.28"
                    width="841.8900146484375"
                    height="595.280029296875"
                >
                    <defs>
                        <style></style>
                    </defs>
                    <title>Artboard 1</title>
                    <g id="Layer_1" data-name="Layer 1">
                        <path
                            class="cls-1 svg-elem-1"
                            d="M293.85,323h-6.7V283.87H275.06v-6.2H306v6.2H293.85Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-2"
                            d="M338.18,291.53a12.37,12.37,0,0,1,3,8.77V323h-6.69V301.05a7.19,7.19,0,0,0-1.8-5.21,7.33,7.33,0,0,0-9.89.12,7.86,7.86,0,0,0-1.83,5.52V323h-6.69V277.74H321V288.9l-.06,6.51h.12a7.62,7.62,0,0,1,2.79-5.27,9.72,9.72,0,0,1,6.2-1.86A10.6,10.6,0,0,1,338.18,291.53Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-3"
                            d="M378.54,307.56H357.71v2.85a8.24,8.24,0,0,0,1.82,5.77,7,7,0,0,0,5.43,2,9,9,0,0,0,4.62-1,4.51,4.51,0,0,0,2.14-3h6.69A10.24,10.24,0,0,1,374,321a15.43,15.43,0,0,1-9.11,2.58q-6.27,0-9.95-3.63a12.83,12.83,0,0,1-3.69-9.58v-8.93a12.81,12.81,0,0,1,3.69-9.61q3.68-3.58,9.95-3.59t10,3.59a12.81,12.81,0,0,1,3.69,9.61ZM357.71,303l14.38-.06v-1.55a8.36,8.36,0,0,0-1.83-5.8,8.12,8.12,0,0,0-10.73,0,8.47,8.47,0,0,0-1.82,5.83Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-4"
                            d="M405.44,323h-6.69V283.87H386.66v-6.2H417.6v6.2H405.44Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-5"
                            d="M452.94,307.56H432.1v2.85a8.24,8.24,0,0,0,1.83,5.77,7,7,0,0,0,5.43,2,9,9,0,0,0,4.62-1,4.51,4.51,0,0,0,2.14-3h6.69a10.24,10.24,0,0,1-4.4,6.91,15.44,15.44,0,0,1-9.12,2.58q-6.26,0-10-3.63a12.82,12.82,0,0,1-3.68-9.58v-8.93a12.8,12.8,0,0,1,3.68-9.61q3.69-3.58,10-3.59t10,3.59a12.81,12.81,0,0,1,3.69,9.61ZM432.1,303l14.39-.06v-1.55a8.36,8.36,0,0,0-1.83-5.8,8.12,8.12,0,0,0-10.73,0,8.47,8.47,0,0,0-1.83,5.83Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-6"
                            d="M487,291.53a12.33,12.33,0,0,1,3,8.77V323h-6.7V301.05a7.23,7.23,0,0,0-1.79-5.21,7.33,7.33,0,0,0-9.89.12,7.86,7.86,0,0,0-1.83,5.52V323h-6.7V288.9h6.64v6.51h.12a7.62,7.62,0,0,1,2.79-5.27,9.72,9.72,0,0,1,6.2-1.86A10.56,10.56,0,0,1,487,291.53Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-7"
                            d="M512.33,323.62a14.3,14.3,0,0,1-8.9-2.58,9.13,9.13,0,0,1-3.69-6.91h6.7a3.9,3.9,0,0,0,1.8,2.79,7.15,7.15,0,0,0,4.09,1.05h2.6a7.2,7.2,0,0,0,4.59-1.24,4.05,4.05,0,0,0,1.55-3.34,3.76,3.76,0,0,0-1.36-3.1,8.54,8.54,0,0,0-4.09-1.55l-4.41-.69c-3.68-.53-6.37-1.58-8.09-3.13a8.61,8.61,0,0,1-2.57-6.72,9,9,0,0,1,3.13-7.32c2.09-1.74,5.12-2.6,9.08-2.6h2.36a13.66,13.66,0,0,1,8.46,2.45,9.09,9.09,0,0,1,3.69,6.6h-6.69a3.79,3.79,0,0,0-1.74-2.48,6.7,6.7,0,0,0-3.72-.93h-2.36q-5.58,0-5.58,4.34a3.44,3.44,0,0,0,1.12,2.79,7.57,7.57,0,0,0,3.72,1.3l4.46.68q5.84.87,8.53,3.26t2.7,6.91a9.48,9.48,0,0,1-3.26,7.69q-3.26,2.73-9.52,2.73Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-8"
                            d="M540.91,320.05q-3.66-3.56-3.66-9.64v-8.93q0-6.08,3.66-9.64t10-3.56q6.33,0,10,3.53t3.65,9.61v9q0,6.07-3.65,9.64t-10,3.57Q544.57,323.62,540.91,320.05ZM556,315.87a7.55,7.55,0,0,0,1.8-5.46v-8.93A7.54,7.54,0,0,0,556,296a8,8,0,0,0-10.29,0,7.54,7.54,0,0,0-1.8,5.45v8.93a7.55,7.55,0,0,0,1.8,5.46,8,8,0,0,0,10.29,0Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-9"
                            d="M600.09,291.66q3.2,3.38,3.19,9.26v2.3H596.4v-1.74a8,8,0,0,0-1.83-5.58,7.6,7.6,0,0,0-10.23,0,8,8,0,0,0-1.83,5.58V323h-6.69V288.9h6.44v6.38q1.62-7,9.18-7A11.31,11.31,0,0,1,600.09,291.66Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-10"
                            d="M615.4,320.05q-3.75-3.56-3.75-9.64V290.32a12.68,12.68,0,0,1,3.75-9.64q3.75-3.56,10.14-3.56t10.07,3.59a12.67,12.67,0,0,1,3.76,9.61h-6.7a7.43,7.43,0,0,0-1.86-5.39,7,7,0,0,0-5.27-1.92,7.17,7.17,0,0,0-5.3,1.89,7.25,7.25,0,0,0-1.89,5.36v20.15a7.34,7.34,0,0,0,1.89,5.39,7.07,7.07,0,0,0,5.3,1.93,7,7,0,0,0,5.24-1.93,7.34,7.34,0,0,0,1.89-5.39h6.7a12.67,12.67,0,0,1-3.76,9.61q-3.75,3.6-10.07,3.6T615.4,320.05Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-11"
                            d="M667,323a10.55,10.55,0,0,1-7.72-2.82,10.08,10.08,0,0,1-2.88-7.54V283.81h-10.3v-6.07h17v34.9a4.25,4.25,0,0,0,1.12,3.13,4,4,0,0,0,3,1.15h11V323Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-12"
                            d="M709.67,291.38a10.35,10.35,0,0,1,3.54,8.3V323H706.7v-6.27h-.07a6.91,6.91,0,0,1-3.31,5,13,13,0,0,1-7.16,1.86,11.9,11.9,0,0,1-8.28-2.76,9.46,9.46,0,0,1-3.07-7.41A9.7,9.7,0,0,1,688,305.7q3.22-2.79,9-2.79h9.49v-3.1a5.41,5.41,0,0,0-1.74-4.31,7.3,7.3,0,0,0-5-1.52,8.27,8.27,0,0,0-4.61,1.15,4.62,4.62,0,0,0-2.14,3.19h-6.58a10.29,10.29,0,0,1,4.22-7.25,15,15,0,0,1,9.24-2.73Q706.14,288.34,709.67,291.38Zm-5.49,25.32a5.63,5.63,0,0,0,2.33-4.74V307.5h-9.36A5.73,5.73,0,0,0,693,309a5.23,5.23,0,0,0-1.51,3.94,5,5,0,0,0,1.76,4.09,7.24,7.24,0,0,0,4.81,1.49A9.8,9.8,0,0,0,704.18,316.7Z"
                        ></path>
                        <path
                            class="cls-1 svg-elem-13"
                            d="M747.37,291.53a12.38,12.38,0,0,1,3,8.77V323h-6.7V301.05a7.19,7.19,0,0,0-1.8-5.21A7.33,7.33,0,0,0,732,296a7.86,7.86,0,0,0-1.83,5.52V323H723.5V288.9h6.63v6.51h.12a7.62,7.62,0,0,1,2.79-5.27,9.75,9.75,0,0,1,6.21-1.86A10.59,10.59,0,0,1,747.37,291.53Z"
                        ></path>
                        <rect
                            class="cls-2 svg-elem-14"
                            x="244.09"
                            y="246.05"
                            width="5.83"
                            height="103.17"
                            rx="2.91"
                        ></rect>
                    </g>
                    <g id="Layer_3" data-name="Layer 3">
                        <path
                            class="cls-3 svg-elem-15"
                            d="M176.68,351.34a.93.93,0,0,1-.57-.19,1,1,0,0,1-.34-1A66.34,66.34,0,0,0,178.12,338v0c.76-7.78.24-18.42-6.55-25-7-6.78-19.79-8.32-24-8.83a63.78,63.78,0,0,0-8.61-.41h-.56c-4.23,0-7.58.06-11.81-2-5.25-2.55-9.49-7.18-12.62-13.77a.94.94,0,0,1,1.58-1,25.28,25.28,0,0,0,7.49,6.23,17.77,17.77,0,0,0,2.08-6.63,1,1,0,0,1,.68-.81,22.19,22.19,0,0,0,3.86-1.54c4.05-2.1,6.3-4.92,8.7-7.92a38.25,38.25,0,0,1,8.79-8.65,34.1,34.1,0,0,1,5.92-3.21,38.44,38.44,0,0,1,8.65-2.44,31.31,31.31,0,0,1,2.36-8.13q.43-1,.93-1.92a31.21,31.21,0,0,1,5.78-7.76.94.94,0,0,1,1.2-.11,27.79,27.79,0,0,1,10.2,13.21,27.3,27.3,0,0,1,1.46,11.91,51.48,51.48,0,0,1,16.55,27.64c3.93,18-3.37,32.42-6.69,37.8h0A51.72,51.72,0,0,1,181.63,348h0l0,0a52.94,52.94,0,0,1-4.42,3.16A1,1,0,0,1,176.68,351.34ZM180,338.13v0a69.33,69.33,0,0,1-1.75,10c.74-.53,1.47-1.07,2.18-1.64h0l0,0a49.8,49.8,0,0,0,11.45-12.85h0c3.2-5.18,10.23-19.1,6.45-36.41a49.6,49.6,0,0,0-16.3-26.92,1,1,0,0,1-.33-.83A25.36,25.36,0,0,0,180.42,258a25.74,25.74,0,0,0-8.86-11.84,29.56,29.56,0,0,0-4.87,6.74c-.3.57-.6,1.18-.87,1.8a29.7,29.7,0,0,0-2.31,8.31.94.94,0,0,1-.81.82,36.15,36.15,0,0,0-8.89,2.42,32.37,32.37,0,0,0-5.59,3,36.57,36.57,0,0,0-8.38,8.27c-2.52,3.15-4.9,6.13-9.3,8.41a23.53,23.53,0,0,1-3.6,1.49,19.93,19.93,0,0,1-2.72,7.56,1,1,0,0,1-1.22.35,24.9,24.9,0,0,1-3.88-2.35,22.73,22.73,0,0,0,8.3,7.1c3.84,1.87,6.83,1.84,11,1.81H139a65.89,65.89,0,0,1,8.85.42c4.36.53,17.61,2.13,25.09,9.34C180.21,318.71,180.8,329.94,180,338.13Zm1,9.15Z"
                        ></path>
                        <path
                            class="cls-4 svg-elem-16"
                            d="M179.07,338.06a32.86,32.86,0,0,0-11.54-21.36c-7.45-6-16.16-6.94-21.72-6.8a25.66,25.66,0,0,0-6.85-7.08,66.54,66.54,0,0,1,8.73.42c4.42.54,17.29,2.09,24.54,9.09C179.17,319,179.88,329.68,179.07,338.06Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-17"
                            d="M179.07,339a.94.94,0,0,1-.94-.82,31.84,31.84,0,0,0-11.2-20.74c-7.08-5.72-15.38-6.73-21.09-6.59a1,1,0,0,1-.83-.44,24.74,24.74,0,0,0-6.6-6.82.94.94,0,0,1,.55-1.71,65.82,65.82,0,0,1,8.84.42c4.36.53,17.61,2.13,25.09,9.34,7.32,7.08,7.91,18.32,7.12,26.51a1,1,0,0,1-.93.85Zm-32.21-30.06c6,0,14.16,1.3,21.26,7a32.41,32.41,0,0,1,10.23,14.9c-.26-6.35-1.9-13.16-6.78-17.86-7-6.78-19.79-8.32-24-8.83-2.2-.26-4.11-.36-5.87-.4a25.56,25.56,0,0,1,4.61,5.17Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-18"
                            d="M132.81,334.53a.95.95,0,0,1-.32-1.84c.56-.19,13.66-4.9,14.84-13.54a13.46,13.46,0,0,0-2.32-8.74,1,1,0,0,1,.3-1.31.94.94,0,0,1,1.3.3,15.16,15.16,0,0,1,2.6,10c-1.33,9.77-15.49,14.85-16.09,15.07A1.12,1.12,0,0,1,132.81,334.53Z"
                        ></path>
                        <path
                            class="cls-5 svg-elem-19"
                            d="M126.08,286.69a18.7,18.7,0,0,1-2.67,7.78,26.06,26.06,0,0,1-8.58-6.88A29.42,29.42,0,0,0,126.08,286.69Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-20"
                            d="M123.41,295.42a.86.86,0,0,1-.41-.1,26.73,26.73,0,0,1-8.89-7.13.92.92,0,0,1-.11-1,.94.94,0,0,1,.92-.5,28.72,28.72,0,0,0,10.89-.87.94.94,0,0,1,.87.18,1,1,0,0,1,.34.83,19.84,19.84,0,0,1-2.8,8.18A1,1,0,0,1,123.41,295.42Zm-6.33-6.74a24.21,24.21,0,0,0,6,4.54,18.22,18.22,0,0,0,1.88-5.25A29.7,29.7,0,0,1,117.08,288.68Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-21"
                            d="M176.68,351.34a.95.95,0,0,1-.47-1.77,24.19,24.19,0,0,0,4.19-3h0l0,0c7.57-6.78,12.88-20.46,7.83-32.5-5.45-13-20.92-17.68-30.09-17.68H158c-1.57,0-3.05.15-5.09.35-3,.29-7,.68-14,.91-6.61.21-10,.06-13.9-1.42a21.1,21.1,0,0,1-2-.88.92.92,0,0,1-.53-.85.94.94,0,0,1,.94-.94,1,1,0,0,1,.48.12c.59.29,1.2.55,1.81.78,3.6,1.37,6.83,1.5,13.17,1.3,6.93-.23,10.95-.62,13.89-.9,2.09-.2,3.6-.35,5.26-.36a41,41,0,0,1,17.43,4.13c6.91,3.39,12,8.47,14.56,14.71,5.4,12.86-.27,27.46-8.34,34.67l0,0a25.69,25.69,0,0,1-4.49,3.21A.93.93,0,0,1,176.68,351.34Z"
                        ></path>
                        <path
                            class="cls-4 svg-elem-22"
                            d="M148.33,283.47c-.54-1,.78-2.78,1.29-3.48A8.32,8.32,0,0,1,152,277.8a29.94,29.94,0,0,1,4.06.38,31.22,31.22,0,0,1,5,1.23,15.69,15.69,0,0,1-6.44,4C152.78,284,149.06,284.75,148.33,283.47Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-23"
                            d="M150.39,285.11c-1.25,0-2.38-.29-2.88-1.18h0c-.85-1.5.63-3.52,1.35-4.5a9.37,9.37,0,0,1,2.65-2.44,1,1,0,0,1,.52-.14,32.49,32.49,0,0,1,4.18.4,32,32,0,0,1,5.11,1.26.93.93,0,0,1,.62.68,1,1,0,0,1-.25.89,16.87,16.87,0,0,1-11.3,5ZM149.16,283c.29.35,2.48.33,5.14-.5a14.42,14.42,0,0,0,4.86-2.67,28.13,28.13,0,0,0-3.25-.71,29.73,29.73,0,0,0-3.64-.37,7.32,7.32,0,0,0-1.88,1.8C149,282.42,149.13,282.93,149.16,283Zm0,0Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-24"
                            d="M153.44,266.28a.94.94,0,0,1-.93-.79,27.05,27.05,0,0,1,0-8.52,27.69,27.69,0,0,1,2.13-7.14,1,1,0,0,1,1-.54,23.43,23.43,0,0,1,5.11,1.48,23,23,0,0,1,4.77,2.75.95.95,0,0,1-1.13,1.52,20.21,20.21,0,0,0-4.38-2.52,20.45,20.45,0,0,0-4-1.23,25.47,25.47,0,0,0-1.67,13.9,1,1,0,0,1-.79,1.08Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-25"
                            d="M179.07,339a1,1,0,0,1-.95-.95h0a.95.95,0,1,1,.95.95Z"
                        ></path>
                        <path
                            class="cls-3 svg-elem-26"
                            d="M123.41,295.42a.94.94,0,0,1-.94-.95h0a.95.95,0,1,1,.94.95Z"
                        ></path>
                    </g>
                </svg>
            </StyledLoader>
        </StyledLoaderContainer>
    );
};

export default Loader;
